### ISSUE TITLE
datetime column does not work for times greater than 99 hours (such as "elapsed" columns)

### ISSUE THREAD

**Issue by stephane-rouleau** [mk-j/PHP_XLSXWriter#106]
In Excel it's possible to use a time column to output large times, such as 1999:19:20 which would be 1999 hours, 19 minutes and 20 seconds. 

Unfortunately, convert_date_time does this RegExp: 

		if (preg_match("/(\d{2}):(\d{2}):(\d{2})/", $date_time, $matches))

it should be modified to be

		if (preg_match("/(\d+):(\d{2}):(\d{2})/", $date_time, $matches))

so that it works properly with single-digits, all the way to uber-digits.

**Comment by mk-j** [comment]
Thanks, this is worth considering, but definitely seems to be an edge case.

**Comment by stephane-rouleau** [comment]
As is often the case with edge cases, it's an edge for some/most people, and 100% hit rate for others (us) :)

I'll fork and create a PR for it I suppose.

**Comment by mk-j** [comment]
An upcoming release/branch includes this.

**Comment by TeeJay-net** [comment]
I'm sorry to say that but @mk-j, this issue is not resolved in the latest version. Could you kindly release one more version with this fix? It's such a simple change and that way, we will not need to fork this project.

**Comment by arthur-olafsson** [comment]
Hi, I'm working on the same project as @TeeJay-net in the above comment.

Since this is fixed on master, we can always get the fix by changing our dependency version to "dev-master". Looking at the master branch, it looks like it's mostly incremental improvements, so it may be quite stable.

I'd appreciate it if you could chime in here, @mk-j, would you advise us to stay away from the master branch for in-production applications?

Btw: Thanks for an awesome library - we're amazed by the performance!
