### ISSUE TITLE
Read Error: Excel found unreadable content in file.xlsx. ...

### ISSUE THREAD

**Issue by seattledeveloper** [mk-j/PHP_XLSXWriter#16]
I am using XLSXWriter to write database data to an Excel spreadsheet.  This is working great for 99% of the data in the database.  Great job!  No PHP memory errors!  I do have one issue however:

I am receiving the "Excel found unreadable content in file.xlsx" message for on 25 row sub set of the data.  I would be happy to send you the file in question.  My database is using ISO-8859-1 encoding, but I am using mb_convert_encoding($field, 'UTF-8', 'windows-1252') to convert the strings.  Any thoughts?

![xlsx-error](https://cloud.githubusercontent.com/assets/9749337/5050662/d2044242-6be4-11e4-8ed4-810704f301fb.gif)

Thanks!

Ed

**Comment by amitrana-dev** [comment]
Not sure if i am doing anything wrong, because got the same error with just writing following headers.
Array
(
    [Status] => string
    [Part Number] => string
    [Model Number] => string
    [Serial Number] => string
    [Manufacturer] => string
    [Condition] => string
    [Vendor] => string
    [Price] => string
    [Purchase Date] => string
    [Warranty Date] => string
    [Calibration Date] => string
)

Code i am using to generate is this:
// $theader output is above
$writer->writeSheetHeader('Sheet1', $theader );
header('Content-disposition: attachment; filename="'.$filename.'"');
header("Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
header('Content-Transfer-Encoding: binary');
$writer->writeToStdOut();

**Comment by mk-j** [comment]
This should be fixed properly in the latest version 0.30
