### ISSUE TITLE
Return stream.

### ISSUE THREAD

**Issue by SamMousa** [mk-j/PHP_XLSXWriter#30]
Currently the only way to get the binary data are the "writeTo" functions.

- writeToFile
- writeToStdOut
- writeToString

With PSR-7 more people will instead be using Streams to model Response in their application.
It would be great if there was a getStream function, that would open a handle to the temporary file with the given parameters.

       public function getStream($mode = 'r') {
               return fopen($this->tempFilename(), $mode, false);
       }

I can implement it and make a pull request if you prefer.

**Comment by mk-j** [comment]
I wouldn't do $this->tempFilename(), that creates a brand new empty temp file.  

Both writeToStdOut and writeToString, call writeToFile internally.  Because xlsx writer has to write a whole bunch of xml files to disk, close the streams then zips them (.xlsx is really just a .zip file), what you probably are looking for is the zip stream, which isn't exposed to the php code anyway.

Perhaps what you are looking for is calling writeToFile("/tmp/mytempfile.xlsx"); then fopen(""/tmp/mytempfile.xlsx", "r", false) for your use case.
