### ISSUE TITLE
PHP 5.3.10 render a non-readable file

### ISSUE THREAD

**Issue by linuxcpp** [mk-j/PHP_XLSXWriter#301]
Hi all,
Following the very first basic example,

PHP 7.* it produce a readable file (*.xlsx) 
but on **PHP 5.3.10** (production env) it produce a non-readable file format (Excel shows an error "File Format or Extension is not valide")
Since the file is on the intranet and cannot be moved to the extranet,
can help or just fix that??

**Comment by linuxcpp** [comment]
ADD： the data from dbselect，encoding utf-8

**Comment by IgorCode** [comment]
I'm not the author but I have to ask: Why waste time and fix issues for EOL product? PHP 5.3 was EOL 7 years ago...

Since you tried the same code on PHP 7 and on PHP 5.3, you could at least have been more helpful with the differences between the two produced files and narrowing down the issue that is causing it to not work.

**Comment by mk-j** [comment]
perhaps display_errors is set to On and php errors and logs are outputting to the xlsx file.  You'd have to look at the raw contents of the xlsx file to see what the issues is with php 5.3.10 compatibility.  Compatibility with php 5.3 is not a high priority.  but you could always trying checking out older releases of this library to see if they work better for you.
