### ISSUE TITLE
WriteToStdOut on Google App Engine

### ISSUE THREAD

**Issue by jcoonrod** [mk-j/PHP_XLSXWriter#51]
How can I use this on Google App Engine to download generated files the way WriteToStdOut works on "normal" hosts? I'm using the example.php file with the headers - it triggers a download of example.xlsx, but that download is always zero bytes.

**Comment by mk-j** [comment]
All that this library does is write some xml files to the /tmp directory
and then zip them up and renames it xlsx.  So if the zip library it uses is
missing it obviously won't work, or it if can't write to /tmp it won't work
either.  If there is a php error, it won't work either.  You'll have to
look into your configuration and see if there is php fatal error or an
exception being through because of the configuration of the system.  I'm
not sure whether errors or written to the syslog, or error_log in google
app engine, but obviously there should be some kind of log for php to write
to.

**Comment by jcoonrod** [comment]
Thanks. GAE does support the ZipArchive class, and no errors are occurring.
And while it definitely cannot write files to /tmp, your code properly
uses sys_get_temp_dir() - which, should allow your routine to work
properly. I'll do some tests and get back to you with suggested changes -
your script is terrific and I would much prefer to use it instead of
phpexcel.

John Coonrod | Executive Vice President | The Hunger Project | +1-917-209-9505
| communitydev.net
