### ISSUE TITLE
emailing formatted data

### ISSUE THREAD

**Issue by bobert13** [mk-j/PHP_XLSXWriter#99]
Hi,

I can't seem to email the data with formatting.
full example here: http://stackoverflow.com/questions/42607831/emailing-formatted-data-with-php-xlsxwriter

What am I missing?

Thanks in advance.

**Comment by mk-j** [comment]
In your example, try:
```
$rowstyle=array('fill'=>"#FC0",'fill'=>"#FC0",'fill'=>"#FC0",'fill'=>"#CCC",'fill'=>"#09F",'fill'=>"#09F",'fill'=>"#09F",'fill'=>"#09F",'fill'=>"#09F",'fill'=>"#09F",'fill'=>"#09F",'fill'=>"#CC9",'fill'=>"#999",'fill'=>"#999",'fill'=>"#999",'fill'=>"#CC9",'fill'=>"#99C",'fill'=>"#99C",'fill'=>"#99C",'fill'=>"#99C",'fill'=>"#9C6",'fill'=>"#9C6");
print_r($rowstyle);
```

it will show a single fill, entry because each fill you have is overwriting the previous one.
try
`$rowstyle=array(['fill'=>"#FC0"],['fill'=>"#FC0"],['fill'=>"#FC0"],['fill'=>"#CCC"],['fill'=>"#09F"],['fill'=>"#09F"],['fill'=>"#09F"],['fill'=>"#09F"],['fill'=>"#09F"],['fill'=>"#09F"],['fill'=>"#09F"],['fill'=>"#CC9"],['fill'=>"#999"],['fill'=>"#999"],['fill'=>"#999"],['fill'=>"#CC9"],['fill'=>"#99C"],['fill'=>"#99C"],['fill'=>"#99C"],['fill'=>"#99C"],['fill'=>"#9C6"],['fill'=>"#9C6"]);`

**Comment by bobert13** [comment]
tried that. still no formatting

**Comment by mk-j** [comment]
I don't know what to tell you. This works for me:
```
<?php
include_once("xlsxwriter.class.php");

$writer = new XLSXWriter();
$rowdata=array('dr1','rp','RoutePattern','TOD','p1','p2','p3','p4','p5','p6','p7','locNames','1D_Minutes','1D_ACD','1W_Minutes','locations','defrate','maxcost','ptLoss','projLoss','modified','description');
$rowstyle=array(['fill'=>"#FC0"],['fill'=>"#FC0"],['fill'=>"#FC0"],['fill'=>"#CCC"],['fill'=>"#09F"],['fill'=>"#09F"],['fill'=>"#09F"],['fill'=>"#09F"],['fill'=>"#09F"],['fill'=>"#09F"],['fill'=>"#09F"],['fill'=>"#CC9"],['fill'=>"#999"],['fill'=>"#999"],['fill'=>"#999"],['fill'=>"#CC9"],['fill'=>"#99C"],['fill'=>"#99C"],['fill'=>"#99C"],['fill'=>"#99C"],['fill'=>"#9C6"],['fill'=>"#9C6"]);
$writer->writeSheetRow('routes', $rowdata, $rowstyle );
$writer->writeSheetRow('routes',array_fill(0, count($rowstyle), 'FILLER') );
$writer->writeSheetRow('routes',array_fill(0, count($rowstyle), 'FILLER') );
$writer->writeSheetRow('routes',array_fill(0, count($rowstyle), 'FILLER') );
$writer->writeToFile('test.xlsx');
```
If this doesn't work for you, I'm not able to reproduce your issue.

**Comment by bobert13** [comment]
issue was that i had an old version of the codebase. updated and now it works.
